cloud:
  aws:
    credentials:
      access-key: xxxxxxxxxxx
      secret-key: xxxxxxxxxxxxxxxx
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: s3FIleStorageSpringbootKaran


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
